<?php
namespace Emis\Exception;

class InternalException extends CoreException
{
    const HTTP_CODE = 500;

    const PACKAGE_NOT_FOUND = 1000;
    const PACKAGE_ALREADY_DEFINED = 1001;
    const PACKAGE_NOT_CONFIGURED = 1002;

    const HTTP_MODULE_NOT_INITIALIZED = 1010;

    const API_METHOD_ERROR_KEYS_FORBIDDEN = 1020;
    const API_METHOD_ERROR_PROPERTIES_FORBIDDEN = 1021;
    const API_METHOD_JSON_FORBIDDEN = 1022;

    const CONFIG_PATH_NOT_SPECIFIED = 1030;
    const CONFIG_SECTION_NOT_FOUND = 1031;
    const CONFIG_VALIDATION_FAILURE = 1032;
    const CONFIG_PATH_NOT_FOUND = 1033;

    const OUTPUT_FORMAT_UNKNOWN = 1040;

    const ENTITY_MANAGER_INVALID_TYPE = 1050;

    const BACKEND_FORWARDED_EXCEPTION = 1060;

    const INVALID_SERIALIZATION_TYPE = 1070;

    const TYPE_PARAMETER_NOT_SPECIFIED = 1080;
    const TYPE_PARAMETER_ASSOC_EXPECTED = 1081;
}
